services:
    web:
        container_name: web
        image: node:14.17.0
        ports: 
            - 3000:3000
        volumes:
          - .:/app/
        command: bash -c "cd /app && sudo rm -rf /node_modules && yarn && yarn run build"
        